- R/utils-wrap.R
Naive attempt to include the last method called in the error message as it is something really useful when the pipeline is quite long:
```r
> as_polars_df(mtcars)$group_by("cyl")$head(-Inf)
Error:
! Evaluation failed in `$head()`.
Caused by error:
! n should not be negative
Run `rlang::last_trace()` to see where the error occurred.
```
Not sure how it would behave with `LazyFrame` since the last method should be `collect()` and the method before that is not necessarily the one that errors.
> feat: improve error message

- src/Makevars.win
Trying to take a look at the progress in `neo-r-polars` but ran into `undefined reference to 'CoTaskMemFree'` when compiling. I remember this was fixed in `r-polars` by one the pkg libs added in this PR but I don't remember which one so I just copy the list from r-polars.
> fix: add missing libraries in makevars.win for windows builds

- R/expr-expr.R
- man/expr__ewm_mean.Rd
- man/expr__ewm_std.Rd
- man/expr__ewm_var.Rd
Addresses https://github.com/eitsupi/neo-r-polars/pull/19#discussion_r1864119287
Now:
> docs: fix math notation in `emw_` functions

- src/rust/Cargo.lock
Ref: https://github.com/eitsupi/neo-r-polars/pull/50#issuecomment-2585308954, rust-lang/cc-rs#1362
I've just run:
```sh
$ pushd src/rust
$ cargo update
$ cargo update cc --precise 1.2.7
```
> chore: update rust deps with `cargo update` and downgrade cc from 1.2.8 to 1.2.7

- R/lazyframe-frame.R
Found while exploring #86 but not a fix unfortunately
> fix: `wrap()` early return in join

- Taskfile.yml
Since we added aliases for formatting, those are the two I use the most.
> build(taskfile): Add aliases for `build-rust` and `build-documents`

- src/rust/src/r_udf.rs
- tests/testthat/_snaps/expr-expr.md
- tests/testthat/test-expr-expr.R
Fix #5
I definitely misunderstood the protection and release of R objects.
I don't think there is any need for special protection on the Rust side since the function object is copied when it is passed.
> fix: Fix `<expr>$map_batches()` crashing R session

- R/lazyframe-frame.R
- man/dataframe__group_by_dynamic.Rd
- man/lazyframe__group_by_dynamic.Rd
* Added a space around `*` so that it's not considered markdown formatting (using `\*` doesn't work as it keeps the backslash in docs)
* Added `@description` so that the second half of the description doesn't end up in "Details"
> docs: Fix formatting and description of `group_by_dynamic()`

- R/dataframe-s3-arrow.R
- R/series-s3-arrow.R
- R/zzz.R
- tests/testthat/_snaps/dataframe-s3-arrow.md
- tests/testthat/_snaps/series-s3-arrow.md
- tests/testthat/test-dataframe-s3-arrow.R
- tests/testthat/test-series-s3-arrow.R
I think it is necessary to recommend the use of `nanoarrow` instead of `arrow` in most cases, which is why they are not documented at this time.
(In other words, when going through nanoarrow_array_stream, it is possible to move between each package with zero-copy, so there is no need to implement methods for functions of the arrow package here.)
> feat: Support converting polars objects to some arrow objects via the Arrow C stream interface

- R/sql-context.R
Fixes the R CMD check warning "checking S3 generic/method consistency"
> fix: Add missing `...` argument in `wrap.PlRSQLContext()`

- R/000-wrappers.R
- R/lazyframe-frame.R
- man/lazyframe__collect.Rd
- src/init.c
- src/rust/api.h
- src/rust/src/conversion/mod.rs
- src/rust/src/lazyframe/general.rs
This argument should eventually be exposed to functions that internally call `collect`, but at this point the new streaming engine has not been activated and decisions regarding API design have not yet been made (#260), so for now it will only be added to `collect()`.
> feat: The new `engine` argument of `<lazyframe>$collect()` to switch query engine

- R/dataframe-frame.R
- man/dataframe__group_by.Rd
This was only present in example for DataFrame, not LazyFrame.
> docs: Fix typo in `group_by()` example

- R/dataframe-s3-base.R
- man/s3-as.list.Rd
- tests/testthat/test-expr-datetime.R
- tests/testthat/test-expr-expr.R
It would be worth changing the default argument so that `as.list(x) |> as_polars_df()` can restore the original DataFrame.
This would be useful when we want to apply some R function on a column-by-column basis in combination with `purrr::map`, etc.
> feat!: Change the default value of `as_series` of `as.list` S3 methods

- .github/workflows/test-r.yml
I think the oldest and newest versions supported here are sufficient.
> ci: Miniaturization of the `R CMD check` test matrix

- R/dataframe-s3-base.R
- tests/testthat/test-dataframe-s3-base.R
> refactor: Remove unused `rlang::` namespace prefix and makes linter happy

- R/dataframe-s3-base.R
- tests/testthat/test-dataframe-s3-base.R
Part of #328
A follow up for #330
> fix: The `drop` argument of `[.polars_data_frame` works correctly for more cases

- altdoc/altdoc_postprocessing.R
For example:
* `groupby__median()` -> `<GroupBy>$median()`
* `lazygroupby__median()` -> `<LazyGroupBy>$median()`
* `sql_context__execute(query)` -> `<SQLContext>$execute(query)`
> docs(altdoc): Better formatting of class names in "Usage" section

- R/dataframe-s3-base.R
- tests/testthat/_snaps/dataframe-s3-base.md
- tests/testthat/test-dataframe-s3-base.R
Part of #328
A follow up for #330
> fix!: Extract (`[`) for DataFrame handles `NULL`, `FALSE` and column names correctly

- R/000-wrappers.R
- R/dataframe-s3-base.R
- R/utils-getitem.R
- src/init.c
- src/rust/api.h
- src/rust/src/dataframe/general.rs
- tests/testthat/_snaps/dataframe-s3-base.md
- tests/testthat/test-dataframe-s3-base.R
Close #328
Previous implementations did not work correctly in the following cases:
``` r
tibble::tibble(a = 1:3)[c(1, NA, 1, 3), ]
#> # A tibble: 4 × 1
#>       a
#>   <int>
#> 1     1
#> 2    NA
#> 3     1
#> 4     3
```
<sup>Created on 2025-05-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> feat: Extract (`[`) for DataFrame handles row index correctly

- DESCRIPTION
This was originally introduced as a countermeasure to the slow build of the `arrow` package from CRAN, but was no longer necessary since the `arrow` package was built faster on R-universe with subsequent CRAN releases.
> chore: Remove the `Additional_repositories` field to reduce build time on R-universe arm64 ubuntu

- R/dataframe-frame.R
- man/dataframe__describe.Rd
- tests/testthat/_snaps/lazyframe-frame.md
Fixes #355 
This was only a mistake for DataFrame, not LazyFrame.
> fix: `describe()` on DataFrame includes 50%

- DESCRIPTION
- man/polars-package.Rd
At the last upgrade, the minor version needed to be set to 9000, but I misread the field and set it to 0.
> chore: Bump package version and set urls

- R/as_polars_df.R
`lengths()` is more readable and more performant:
``` r
my_list <- rep(list(1:10), 10000)
bench::mark(
vapply = vapply(my_list, length, integer(1)) |>
unique(),
lengths = unique(lengths(my_list))
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vapply       1.47ms   1.51ms      640.     206KB     35.2
#> 2 lengths    103.92µs 107.01µs     8190.     206KB     29.4
```
> refactor: Use the `lengths()` function to get each length of list elements

- R/000-wrappers.R
- R/dataframe-frame.R
- R/lazyframe-frame.R
- man/dataframe__join.Rd
- man/lazyframe__join.Rd
- src/init.c
- src/rust/api.h
- src/rust/src/lazyframe/general.rs
- tests/testthat/test-lazyframe-frame.R
> fix!: The `join_nulls` arguments are renamed to `nulls_equal` like Python Polars

- R/000-wrappers.R
- R/expr-meta.R
- man/expr_meta_tree_format.Rd
- src/init.c
- src/rust/api.h
- src/rust/src/expr/meta.rs
> fix: Expose the `schema` argument of `compute_tree_format` to the R side and mark `as_dot` as experimental

- R/expr-string.R
- man/expr_str_extract.Rd
- tests/testthat/test-expr-string.R
Fix pola-rs/r-polars#1418
- Fix the default value of `group_index`.
- `<expr>$str$extract()` should treat the `pattern` as a literal expr.
> fix!: Fix `<expr>$str$extract()`'s arguments to match Python Polars behavior
