src/rust/Cargo.toml
tests/testthat/test-lazyframe-frame.R

feat: Enable cross joins

---

.Rbuildignore
.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json
Taskfile.yml
air.toml

Related to #73
The actual formatting has not yet been done. (I would like to do this after this is merged.)

build: Add settings for the Air formatter for R files

---

R/lazyframe-frame.R
man/lazyframe__sink_csv.Rd

Should fix the [failures in R-universe](https://github.com/r-universe/eitsupi/actions/runs/13546016946/job/37859000810)

docs: Fix examples of `sink_csv()`

---

R/000-wrappers.R
R/dataframe-s3-nanoarrow.R
R/series-s3-nanoarrow.R
R/utils-check.R
man/s3-as_nanoarrow_array_stream.Rd
src/init.c
src/rust/api.h
src/rust/src/conversion/mod.rs
src/rust/src/series/export.rs
tests/testthat/_snaps/dataframe-s3-nanoarrow.md
tests/testthat/_snaps/series-s3-nanoarrow.md
tests/testthat/test-dataframe-s3-nanoarrow.R
tests/testthat/test-series-s3-nanoarrow.R

Related to pola-rs/polars#18210
@etiennebacher You may want to check this.

feat: Support specifying polars-arrow compat level in `nanoarrow::as_nanoarrow_array_stream()`

---

NEWS.md
R/as_polars_df.R
R/as_polars_lf.R
R/as_polars_series.R
R/infer_polars_dtype.R
R/utils-check.R
R/utils-parse-datatype.R
tests/testthat/_snaps/as_polars_df.md
tests/testthat/_snaps/as_polars_lf.md
tests/testthat/_snaps/as_polars_series.md
tests/testthat/_snaps/dataframe-s3-arrow.md
tests/testthat/_snaps/dataframe-s3-nanoarrow.md
tests/testthat/_snaps/expr-expr.md
tests/testthat/_snaps/expr-meta.md
tests/testthat/_snaps/functions-as_datatype.md
tests/testthat/_snaps/infer_polars_dtype.md
tests/testthat/_snaps/series-s3-nanoarrow.md
tests/testthat/test-as_polars_lf.R
tests/testthat/test-as_polars_series.R
tests/testthat/test-lazyframe-frame.R

feat: Better error messages for the default methods of `as_polars_df()`, `as_polars_series()` and `infer_polars_dtype()`

---

tests/testthat/test-lazyframe-frame.R
tests/testthat/test-sql-context.R

Also save some space in a few SQL queries.

test: Check message pattern in a `SQLContext()` test

---

DESCRIPTION

fix: Bump depending R version to the actual supported version

---

.github/workflows/test-r.yml
DESCRIPTION

ci: Simplify jobs for faster testing

---

src/Makevars.in
src/Makevars.win.in

build: Fix for multiple runs of `pkgbuild::compile_dll()` etc. to work fine

---

.Rbuildignore

refactor: Minor fix of .Rbuildignore syntax (requires savvy-cli 0.8.8)

---

R/000-wrappers.R
R/as_polars_expr.R
R/as_polars_series.R
R/selectors.R
man/as_polars_expr.Rd
man/as_polars_series.Rd
man/cs__binary.Rd
src/init.c
src/rust/api.h
src/rust/src/functions/lazy.rs
src/rust/src/series/construction.rs
tests/testthat/_snaps/as_polars_series.md
tests/testthat/test-as_polars_expr.R
tests/testthat/test-as_polars_series.R
tests/testthat/test-selectors.R

feat!: Convert raw vector to uint8 sereis and convert raw vector to binary scalar expr by default

---

R/000-wrappers.R
R/dataframe-s3-base.R
R/dataframe-s3-tibble.R
R/series-to_r_vector.R
man/s3-as.data.frame.Rd
man/s3-as.list.Rd
man/s3-as_tibble.Rd
man/series__to_r_vector.Rd
src/init.c
src/rust/api.h
src/rust/src/conversion/chunked_array.rs
src/rust/src/series/export.rs
tests/testthat/test-series-to_r_vector.R

feat: Add an option to export uint8 type series as raw vector

---

man/lazyframe__select_seq.Rd
tests/testthat/_snaps/output-ipc-functions.md

@eitsupi I don't know why but the snapshot tests you added in #200 produce weird output for me.
Also this redocuments following #247.

docs: Regenerate Rd files

---

src/rust/src/conversion/chunked_array.rs
src/rust/src/conversion/clock.rs
src/rust/src/conversion/data_table.rs
src/rust/src/series/export.rs

perf: Skip Owned Sexp initialization while conversion

---

src/rust/Cargo.lock

chore: Bump savvy to 0.8.9

---

.github/workflows/test-r.yml

ci: Tests on R devel with debug profile to detect C-level changes

---

R/dataframe-s3-arrow.R
R/dataframe-s3-nanoarrow.R
R/dataframe-s3-tibble.R
R/dataframe-s3-waldo.R
R/datatypes-s3-waldo.R
R/expr-s3-waldo.R
R/lazyframe-s3-tibble.R
R/series-s3-arrow.R
R/series-s3-nanoarrow.R
R/series-s3-waldo.R

chore: Fix some lintr's lint errors (S3 methods exported by the `s3_register` function)

---

R/api.R
R/dataframe-group_by-rolling.R
R/dataframe-group_by_dynamic.R
R/datatypes-s3-base.R
R/expr-list.R
R/expr-s3-operators.R
R/generated-s3methods-dollar.R
R/generated-s3methods-series-namespace-dollar.R
R/infer_polars_dtype.R
R/series-categorical.R
R/utils-parse-expr.R
dev/generate-r-files/templates/s3methods-dollar.R.txt
dev/generate-r-files/templates/s3methods-series-namespace-dollar.R.txt

chore: Fix some lintr's lint errors (disable useless lints by special comments)

---

src/rust/Cargo.lock
src/rust/Cargo.toml

(Maybe) Fix pola-rs/r-polars#1381

feat: Enable cloud provider features for to scan files from cloud

---

README.Rmd
README.md

- Do not use code font for package names (See <https://style.tidyverse.org/documentation.html#package-names>)
- Link to polars0 repo

docs(readme): Polish README

---

R/as_polars_expr.R
tests/testthat/_snaps/as_polars_expr.md
tests/testthat/test-as_polars_expr.R

feat!: Keep name of the Series when converting to scalar expr by `as_polars_expr()`

---

DEVELOPMENT.md

docs(development): Add notes about tools and tests

---

R/000-wrappers.R
R/expr-string.R
man/expr_str_json_decode.Rd
src/init.c
src/rust/api.h
src/rust/src/expr/string.rs

fix: `<expr>$str$json_decode()` accepts `NULL` for the first argument

---

R/expr-datetime.R
man/expr_dt_second.Rd

fix!: The `fractional` argument of `<expr>$dt$second()` must be named

---

R/dataframe-frame.R
R/expr-expr.R
R/lazyframe-frame.R
R/utils-check.R
man/dataframe__fill_null.Rd
man/expr__fill_null.Rd
man/lazyframe__fill_null.Rd
tests/testthat/test-lazyframe-frame.R

fix: Fix the default argument of `$fill_null()` of expr, lazyframe, dataframe

---

R/expr-meta.R
man/expr_meta_pop.Rd

fix: Expose the `schema` argument of `<expr>$meta$pop()`

---

R/expr-expr.R
man/expr__and.Rd
man/expr__or.Rd
tests/testthat/test-expr-expr.R

Fixes https://github.com/pola-rs/r-polars/issues/1417

fix: Update arguments of `$and()` and `$or()` to match Python Polars
